# Generated by Django 6.0.2 on 2026-03-09 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего продления'),
        ),
        migrations.AddField(
            model_name='loan',
            name='max_renewals',
            field=models.IntegerField(default=2, verbose_name='Макс. количество продлений'),
        ),
        migrations.AddField(
            model_name='loan',
            name='renewal_count',
            field=models.IntegerField(default=0, verbose_name='Количество продлений'),
        ),
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('due_date', models.DateField()),
                ('was_overdue', models.BooleanField(default=False)),
                ('days_overdue', models.IntegerField(blank=True, default=0, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История находок',
                'verbose_name_plural': 'Истории находок',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('request_approved', 'Запрос одобрен'), ('request_rejected', 'Запрос отклонен'), ('due_soon', 'Срок приближается'), ('overdue', 'Просрочена'), ('available', 'Книга доступна'), ('renewal_available', 'Доступно продление')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('content', models.TextField(verbose_name='Содержание отзыва')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_date'],
                'unique_together': {('reader', 'book')},
            },
        ),
    ]
