# Generated by Django 6.0.2 on 2026-03-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_loan_last_renewal_date_loan_max_renewals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_book',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='last_renewal_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='max_renewals',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='renewal_count',
        ),
        migrations.DeleteModel(
            name='BorrowHistory',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
